import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Navbar from '../components/navbar';
import AppList from '../components/AppList';

const apps = [
    'app1',
    'app2',
    'app3'
];

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>App Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
            </Head>
            <body>
                <Navbar />
                <section className="section">
                    <div className="container">
                        <h1 className="title">
                            Web Application Directory
                        </h1>
                        <p className="subtitle">
                            Welcome to the home of my personal web applications.
                        </p>
                    </div>
                </section>
                <section className="section">
                    <AppList apps={apps} />
                </section>
            </body>
        </div>
    )
}

export default Home
