name: VPS Deploy Export

on:
  push:
    branches: [ main ]

jobs:
   deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - name: Build app
        run: |
          npm ci
          npm run css-build
          npm run export

      - name: Deploy app
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          DEST: "admin@rosghub.xyz:/var/www/vps-home"
        run: |
          mkdir -p ~/.ssh
          echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts
          echo "${PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod -R 700 ~/.ssh
          rsync -avz --delete out "${DEST}"